### ISSUE TITLE
Creating a VM with the openstack playbook fails

### ISSUE THREAD

**Issue by jacobdotcosta** [snowdrop/k8s-infra#175] opened 2020-11-25 15:26 UTC
When creating a VM using the openstack playbook, the process fails.

**Comment by cmoulliard** [comment] 2021-04-15 08:13
Wont fix as we cannot reproduce. VM created successfully `April 10, 2021, 7:39 a.m.` using the following command
```
ansible-playbook playbook/openstack.yml -e '{"state": "present","hostname": "n119-test","openstack": {"os_username": "ttttt","os_domain": "yyyyy", "os_password": "xxxxx","os_auth_url": "https://rhos-d.infra.prod.upshift.rdu2.redhat.com:13000/v3/","vm": {"network": "provider_net_shared", "security_group": "spring-boot",  "flavor": "ci.m5.large", "volumes" : ["test-volume"]}}}' -e type=cloud
```

**Closed by cmoulliard** 2021-04-15 08:13 UTC
Labels: 3 - Team work
